### ISSUE TITLE
How are lua systems forced to run on the main thread?

### ISSUE THREAD

**Issue by sro5h** [flecs-hub/flecs-lua#11]
I saw that in [system.c](https://github.com/flecs-hub/flecs-lua/blob/1c63d084c6df82c8627f81a215e52304e1866a0b/src/system.c#L40) there is an assert to make sure that lua systems are run on the main thread:
```c
ecs_assert(stage_id == 0, ECS_INTERNAL_ERROR, "Lua callbacks must run on the main thread");
```
But i can't find any code that actually disables multithreading while initializing lua systems or for the world as a whole. Am i missing something?

**Comment by randy408** [comment]
For v3 there is a new `ecs_system_desc_t.multi_threaded`, it's initialized to `0` (i.e. `false`) by default, that's why you don't see any specific code for that.

That assert is from the v2 days where you either disabled threading or scheduled the systems on your own, there was no per-system scheduling option.
